### PR TITLE
Updated the file to work in regular javascript and not require JQuery

### PR DESCRIPTION
**Pull request by neilkennedy**
Instructions have been updated in the readme

fartscroll(document, 800);

### CODE REVIEW

**Comment by csinchok** [comment]
I like it. I'll take a look at this tonight.

**Comment by michaelficarra** [comment]
:+1:!

**Comment by jonathanong** [comment]
oh nice! +1

**Comment by csinchok** [comment]
Hey, @neilkennedy, I merged this in d81a45ed8e52b45832390d3c101ac6b1f061d0dd. That kinda got lost, because I'm not great with pull requests yet.

Thanks for your patch, and your commitment to open source flatulence technology!

**Comment by neilkennedy** [comment]
Nice! With the level of interest this is getting I'm sure you'll be a pull request ninja in no time.

**Pull request closed without merging**
