### PR TITLE
Never stop a good fart in progress.

### PR DESCRIPTION
**Pull request by gweedo767**
Simply adds an addEventListener for ended before letting a new fart get started.  This is helpful for very low trigger_distance values.

### CODE REVIEW

**Comment by gweedo767** [comment]
Didn't mean to include all the reverts, they were just me matching the original formatting.

**Comment by imnotjames** [comment]
Why not remove them?

**Comment by gweedo767** [comment]
Because, meh.

**Comment by csinchok** [comment]
Commit d81a45ed8e52b45832390d3c101ac6b1f061d0dd allows farts to overlap each other unimpeded. Possibly this could be considered an "interruption", but I think simultaneous farts are the future.

**Comment by gweedo767** [comment]
I happily bow to the greatness of multi-farts.

**Pull request closed without merging**
