### PR TITLE
adding bookmarklet

### PR DESCRIPTION
**Pull request by pjkix**
fixes Issue #25

### CODE REVIEW

**Comment by csinchok** [comment]
I like this. I'll add it to the site soon, but first I'm gonna start versioning the JS, and hosting it on a CDN—that'll help with the bookmarklet, as github's raw view doesn't set the proper MIME type, which can cause issues.

**Comment by michaelficarra** [comment]
For the correct MIME type, just use [rawgithub.com](http://rawgithub.com/).

https://rawgithub.com/theonion/fartscroll.js/master/fartscroll.js

**Comment by vendethiel** [comment]
@michaelficarra added in my bookmarks, thanks :).

**Comment by csinchok** [comment]
I added a bookmarklet link on the project page, thanks!

**Pull request closed without merging**
